# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Matt Horn
title: Software Engineer
email: matt@matthorn.io
website: matthorn.io

# Social links
# twitter_username: facespics
github_username:  matthorn-repo
# dribbble_username: jekyll
facebook_username: matt.horn.359
# flickr_username: jekyll
instagram_username: matt.horn.22
linkedin_username: matt-horn-718611197
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Matt and I'm a software engineer. Most of my expertise is with large scale software design
  and implementation at companies like <mark>Amazon</mark> and <mark>Google</mark>. I'm an AWS Certified Soltuions Architect and
  I also have experience with Google cloud. I love solving backend design problems for systems that need
  to scale fast.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  I live in Colorado and have a dog named Atlas. When I'm not writing code, you'll find me:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
